// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protocols/scheduler/v1alpha/scheduler.proto

package scheduler

import (
	intent "github.com/neuro-fluidic-architecture/nfa-core/go/protos/intent/v1alpha"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntentRequest   *intent.IntentRequest `protobuf:"bytes,1,opt,name=intent_request,json=intentRequest,proto3" json:"intent_request,omitempty"`
	ResourceRequest *ResourceRequest      `protobuf:"bytes,2,opt,name=resource_request,json=resourceRequest,proto3" json:"resource_request,omitempty"`
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_scheduler_v1alpha_scheduler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_scheduler_v1alpha_scheduler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// 省略其他生成的代码...

// 调度策略枚举
type SchedulingPolicy int32

const (
	SchedulingPolicy_SCHEDULING_POLICY_UNSPECIFIED     SchedulingPolicy = 0
	SchedulingPolicy_SCHEDULING_POLICY_PERFORMANCE_FIRST SchedulingPolicy = 1
	SchedulingPolicy_SCHEDULING_POLICY_ENERGY_EFFICIENT SchedulingPolicy = 2
	SchedulingPolicy_SCHEDULING_POLICY_LATENCY_SENSITIVE SchedulingPolicy = 3
	SchedulingPolicy_SCHEDULING_POLICY_COST_OPTIMIZED   SchedulingPolicy = 4
)

// Enum value maps for SchedulingPolicy.
var (
	SchedulingPolicy_name = map[int32]string{
		0: "SCHEDULING_POLICY_UNSPECIFIED",
		1: "SCHEDULING_POLICY_PERFORMANCE_FIRST",
		2: "SCHEDULING_POLICY_ENERGY_EFFICIENT",
		3: "SCHEDULING_POLICY_LATENCY_SENSITIVE",
		4: "SCHEDULING_POLICY_COST_OPTIMIZED",
	}
	SchedulingPolicy_value = map[string]int32{
		"SCHEDULING_POLICY_UNSPECIFIED":     0,
		"SCHEDULING_POLICY_PERFORMANCE_FIRST": 1,
		"SCHEDULING_POLICY_ENERGY_EFFICIENT": 2,
		"SCHEDULING_POLICY_LATENCY_SENSITIVE": 3,
		"SCHEDULING_POLICY_COST_OPTIMIZED":   4,
	}
)

func (x SchedulingPolicy) Enum() *SchedulingPolicy {
	p := new(SchedulingPolicy)
	*p = x
	return p
}

func (x SchedulingPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedulingPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_protocols_scheduler_v1alpha_scheduler_proto_enumTypes[0].Descriptor()
}

func (SchedulingPolicy) Type() protoreflect.EnumType {
	return &file_protocols_scheduler_v1alpha_scheduler_proto_enumTypes[0]
}

func (x SchedulingPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}