// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protocols/intent/v1alpha/intent.proto

package intent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntentPattern struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pattern    *IntentPattern_Pattern    `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Constraints *IntentPattern_Constraints `protobuf:"bytes,2,opt,name=constraints,proto3" json:"constraints,omitempty"`
}

func (x *IntentPattern) Reset() {
	*x = IntentPattern{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_intent_v1alpha_intent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntentPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentPattern) ProtoMessage() {}

func (x *IntentPattern) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_intent_v1alpha_intent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// 省略其他生成的代码...

type IntentContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  string     `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Kind     string     `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata *Metadata  `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec     *IntentSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *IntentContract) Reset() {
	*x = IntentContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_intent_v1alpha_intent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntentContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentContract) ProtoMessage() {}

func (x *IntentContract) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_intent_v1alpha_intent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}