# NFA Core 默认配置

[broker]
listen_address = "0.0.0.0:50051"
max_connections = 1000
heartbeat_timeout_secs = 30
storage_backend = "memory"

# Redis 配置（如果使用Redis存储后端）
[broker.redis]
url = "redis://localhost:6379"
prefix = "nfa"

# PostgreSQL 配置（如果使用PostgreSQL存储后端）
[broker.postgres]
url = "postgres://user:password@localhost:5432/nfa"
table_prefix = "nfa_"

[scheduler]
policy = "balanced"
resource_check_interval_secs = 5
max_concurrent_schedules = 100
cost_weight = 0.3
latency_weight = 0.4
energy_weight = 0.3

[storage]
max_retention_days = 30
backup_interval_secs = 3600
cleanup_interval_secs = 86400

[network]
timeout_secs = 10
retry_attempts = 3
retry_delay_secs = 1
max_message_size = 10485760  # 10MB

[logging]
level = "info"
format = "json"
file = "/var/log/nfa/core.log"

[monitoring]
enabled = true
prometheus_port = 9090
health_check_port = 8080
metrics_interval_secs = 15

[tracing]
enabled = true
jaeger_endpoint = "http://localhost:14268/api/traces"
sampling_rate = 0.1

[auth]
enabled = false
jwt_secret = "change-me-in-production"
token_expiry_hours = 24

# 开发模式配置
[dev]
hot_reload = true
debug_endpoints = true
mock_services = false